/* eslint-disable quotes */

export const rolesTabInitData = `insert into roles (id,role) values (gen_random_uuid(),'Admin'),(gen_random_uuid(),'User');`;

export const countriesTabInitData = `insert into countries (id,name,dial_code,country_code) values (gen_random_uuid(),'India','+91','IN'),(gen_random_uuid(),'United States of America','+1','US'),(gen_random_uuid(),'Afghanistan','+93','AF'),
(gen_random_uuid(),'Aland Islands','+358','AX'),
(gen_random_uuid(),'Albania','+355','AL'),
(gen_random_uuid(),'Algeria','+213','DZ'),
(gen_random_uuid(),'AmericanSamoa','+1684','AS'),
(gen_random_uuid(),'Andorra','+376','AD'),
(gen_random_uuid(),'Angola','+244','AO'),
(gen_random_uuid(),'Anguilla','+1264','AI'),
(gen_random_uuid(),'Antarctica','+672','AQ'),
(gen_random_uuid(),'Antigua and Barbuda','+1268','AG'),
(gen_random_uuid(),'Argentina','+54','AR'),
(gen_random_uuid(),'Armenia','+374','AM'),
(gen_random_uuid(),'Aruba','+297','AW'),
(gen_random_uuid(),'Australia','+61','AU'),
(gen_random_uuid(),'Austria','+43','AT'),
(gen_random_uuid(),'Azerbaijan','+994','AZ'),
(gen_random_uuid(),'Bahamas','+1242','BS'),
(gen_random_uuid(),'Bahrain','+973','BH'),
(gen_random_uuid(),'Bangladesh','+880','BD'),
(gen_random_uuid(),'Barbados','+1246','BB'),
(gen_random_uuid(),'Belarus','+375','BY'),
(gen_random_uuid(),'Belgium','+32','BE'),
(gen_random_uuid(),'Belize','+501','BZ'),
(gen_random_uuid(),'Benin','+229','BJ'),
(gen_random_uuid(),'Bermuda','+1441','BM'),
(gen_random_uuid(),'Bhutan','+975','BT'),
(gen_random_uuid(),'Bolivia, Plurinational State of','+591','BO'),
(gen_random_uuid(),'Bosnia and Herzegovina','+387','BA'),
(gen_random_uuid(),'Botswana','+267','BW'),
(gen_random_uuid(),'Brazil','+55','BR'),
(gen_random_uuid(),'British Indian Ocean Territory','+246','IO'),
(gen_random_uuid(),'Brunei Darussalam','+673','BN'),
(gen_random_uuid(),'Bulgaria','+359','BG'),
(gen_random_uuid(),'Burkina Faso','+226','BF'),
(gen_random_uuid(),'Burundi','+257','BI'),
(gen_random_uuid(),'Cambodia','+855','KH'),
(gen_random_uuid(),'Cameroon','+237','CM'),
(gen_random_uuid(),'Canada','+1','CA'),
(gen_random_uuid(),'Cape Verde','+238','CV'),
(gen_random_uuid(),'Cayman Islands','+ 345','KY'),
(gen_random_uuid(),'Central African Republic','+236','CF'),
(gen_random_uuid(),'Chad','+235','TD'),
(gen_random_uuid(),'Chile','+56','CL'),
(gen_random_uuid(),'China','+86','CN'),
(gen_random_uuid(),'Christmas Island','+61','CX'),
(gen_random_uuid(),'Cocos (Keeling) Islands','+61','CC'),
(gen_random_uuid(),'Colombia','+57','CO'),
(gen_random_uuid(),'Comoros','+269','KM'),
(gen_random_uuid(),'Congo','+242','CG'),
(gen_random_uuid(),'Congo, The Democratic Republic of the Congo','+243','CD'),
(gen_random_uuid(),'Cook Islands','+682','CK'),
(gen_random_uuid(),'Costa Rica','+506','CR'),
(gen_random_uuid(),'Cote d''Ivoire','+225','CI'),
(gen_random_uuid(),'Croatia','+385','HR'),
(gen_random_uuid(),'Cuba','+53','CU'),
(gen_random_uuid(),'Cyprus','+357','CY'),
(gen_random_uuid(),'Czech Republic','+420','CZ'),
(gen_random_uuid(),'Denmark','+45','DK'),
(gen_random_uuid(),'Djibouti','+253','DJ'),
(gen_random_uuid(),'Dominica','+1767','DM'),
(gen_random_uuid(),'Dominican Republic','+1849','DO'),
(gen_random_uuid(),'Ecuador','+593','EC'),
(gen_random_uuid(),'Egypt','+20','EG'),
(gen_random_uuid(),'El Salvador','+503','SV'),
(gen_random_uuid(),'Equatorial Guinea','+240','GQ'),
(gen_random_uuid(),'Eritrea','+291','ER'),
(gen_random_uuid(),'Estonia','+372','EE'),
(gen_random_uuid(),'Ethiopia','+251','ET'),
(gen_random_uuid(),'Falkland Islands (Malvinas)','+500','FK'),
(gen_random_uuid(),'Faroe Islands','+298','FO'),
(gen_random_uuid(),'Fiji','+679','FJ'),
(gen_random_uuid(),'Finland','+358','FI'),
(gen_random_uuid(),'France','+33','FR'),
(gen_random_uuid(),'French Guiana','+594','GF'),
(gen_random_uuid(),'French Polynesia','+689','PF'),
(gen_random_uuid(),'Gabon','+241','GA'),
(gen_random_uuid(),'Gambia','+220','GM'),
(gen_random_uuid(),'Georgia','+995','GE'),
(gen_random_uuid(),'Germany','+49','DE'),
(gen_random_uuid(),'Ghana','+233','GH'),
(gen_random_uuid(),'Gibraltar','+350','GI'),
(gen_random_uuid(),'Greece','+30','GR'),
(gen_random_uuid(),'Greenland','+299','GL'),
(gen_random_uuid(),'Grenada','+1473','GD'),
(gen_random_uuid(),'Guadeloupe','+590','GP'),
(gen_random_uuid(),'Guam','+1671','GU'),
(gen_random_uuid(),'Guatemala','+502','GT'),
(gen_random_uuid(),'Guernsey','+44','GG'),
(gen_random_uuid(),'Guinea','+224','GN'),
(gen_random_uuid(),'Guinea-Bissau','+245','GW'),
(gen_random_uuid(),'Guyana','+595','GY'),
(gen_random_uuid(),'Haiti','+509','HT'),
(gen_random_uuid(),'Holy See (Vatican City State)','+379','VA'),
(gen_random_uuid(),'Honduras','+504','HN'),
(gen_random_uuid(),'Hong Kong','+852','HK'),
(gen_random_uuid(),'Hungary','+36','HU'),
(gen_random_uuid(),'Iceland','+354','IS'),
(gen_random_uuid(),'Indonesia','+62','ID'),
(gen_random_uuid(),'Iran, Islamic Republic of Persian Gulf','+98','IR'),
(gen_random_uuid(),'Iraq','+964','IQ'),
(gen_random_uuid(),'Ireland','+353','IE'),
(gen_random_uuid(),'Isle of Man','+44','IM'),
(gen_random_uuid(),'Israel','+972','IL'),
(gen_random_uuid(),'Italy','+39','IT'),
(gen_random_uuid(),'Jamaica','+1876','JM'),
(gen_random_uuid(),'Japan','+81','JP'),
(gen_random_uuid(),'Jersey','+44','JE'),
(gen_random_uuid(),'Jordan','+962','JO'),
(gen_random_uuid(),'Kazakhstan','+77','KZ'),
(gen_random_uuid(),'Kenya','+254','KE'),
(gen_random_uuid(),'Kiribati','+686','KI'),
(gen_random_uuid(),'Korea, Democratic People''s Republic of Korea','+850','KP'),
(gen_random_uuid(),'Korea, Republic of South Korea','+82','KR'),
(gen_random_uuid(),'Kuwait','+965','KW'),
(gen_random_uuid(),'Kyrgyzstan','+996','KG'),
(gen_random_uuid(),'Laos','+856','LA'),
(gen_random_uuid(),'Latvia','+371','LV'),
(gen_random_uuid(),'Lebanon','+961','LB'),
(gen_random_uuid(),'Lesotho','+266','LS'),
(gen_random_uuid(),'Liberia','+231','LR'),
(gen_random_uuid(),'Libyan Arab Jamahiriya','+218','LY'),
(gen_random_uuid(),'Liechtenstein','+423','LI'),
(gen_random_uuid(),'Lithuania','+370','LT'),
(gen_random_uuid(),'Luxembourg','+352','LU'),
(gen_random_uuid(),'Macao','+853','MO'),
(gen_random_uuid(),'Macedonia','+389','MK'),
(gen_random_uuid(),'Madagascar','+261','MG'),
(gen_random_uuid(),'Malawi','+265','MW'),
(gen_random_uuid(),'Malaysia','+60','MY'),
(gen_random_uuid(),'Maldives','+960','MV'),
(gen_random_uuid(),'Mali','+223','ML'),
(gen_random_uuid(),'Malta','+356','MT'),
(gen_random_uuid(),'Marshall Islands','+692','MH'),
(gen_random_uuid(),'Martinique','+596','MQ'),
(gen_random_uuid(),'Mauritania','+222','MR'),
(gen_random_uuid(),'Mauritius','+230','MU'),
(gen_random_uuid(),'Mayotte','+262','YT'),
(gen_random_uuid(),'Mexico','+52','MX'),
(gen_random_uuid(),'Micronesia, Federated States of Micronesia','+691','FM'),
(gen_random_uuid(),'Moldova','+373','MD'),
(gen_random_uuid(),'Monaco','+377','MC'),
(gen_random_uuid(),'Mongolia','+976','MN'),
(gen_random_uuid(),'Montenegro','+382','ME'),
(gen_random_uuid(),'Montserrat','+1664','MS'),
(gen_random_uuid(),'Morocco','+212','MA'),
(gen_random_uuid(),'Mozambique','+258','MZ'),
(gen_random_uuid(),'Myanmar','+95','MM'),
(gen_random_uuid(),'Namibia','+264','NA'),
(gen_random_uuid(),'Nauru','+674','NR'),
(gen_random_uuid(),'Nepal','+977','NP'),
(gen_random_uuid(),'Netherlands','+31','NL'),
(gen_random_uuid(),'Netherlands Antilles','+599','AN'),
(gen_random_uuid(),'New Caledonia','+687','NC'),
(gen_random_uuid(),'New Zealand','+64','NZ'),
(gen_random_uuid(),'Nicaragua','+505','NI'),
(gen_random_uuid(),'Niger','+227','NE'),
(gen_random_uuid(),'Nigeria','+234','NG'),
(gen_random_uuid(),'Niue','+683','NU'),
(gen_random_uuid(),'Norfolk Island','+672','NF'),
(gen_random_uuid(),'Northern Mariana Islands','+1670','MP'),
(gen_random_uuid(),'Norway','+47','NO'),
(gen_random_uuid(),'Oman','+968','OM'),
(gen_random_uuid(),'Pakistan','+92','PK'),
(gen_random_uuid(),'Palau','+680','PW'),
(gen_random_uuid(),'Palestinian Territory, Occupied','+970','PS'),
(gen_random_uuid(),'Panama','+507','PA'),
(gen_random_uuid(),'Papua New Guinea','+675','PG'),
(gen_random_uuid(),'Paraguay','+595','PY'),
(gen_random_uuid(),'Peru','+51','PE'),
(gen_random_uuid(),'Philippines','+63','PH'),
(gen_random_uuid(),'Pitcairn','+872','PN'),
(gen_random_uuid(),'Poland','+48','PL'),
(gen_random_uuid(),'Portugal','+351','PT'),
(gen_random_uuid(),'Puerto Rico','+1939','PR'),
(gen_random_uuid(),'Qatar','+974','QA'),
(gen_random_uuid(),'Romania','+40','RO'),
(gen_random_uuid(),'Russia','+7','RU'),
(gen_random_uuid(),'Rwanda','+250','RW'),
(gen_random_uuid(),'Reunion','+262','RE'),
(gen_random_uuid(),'Saint Barthelemy','+590','BL'),
(gen_random_uuid(),'Saint Helena, Ascension and Tristan Da Cunha','+290','SH'),
(gen_random_uuid(),'Saint Kitts and Nevis','+1869','KN'),
(gen_random_uuid(),'Saint Lucia','+1758','LC'),
(gen_random_uuid(),'Saint Martin','+590','MF'),
(gen_random_uuid(),'Saint Pierre and Miquelon','+508','PM'),
(gen_random_uuid(),'Saint Vincent and the Grenadines','+1784','VC'),
(gen_random_uuid(),'Samoa','+685','WS'),
(gen_random_uuid(),'San Marino','+378','SM'),
(gen_random_uuid(),'Sao Tome and Principe','+239','ST'),
(gen_random_uuid(),'Saudi Arabia','+966','SA'),
(gen_random_uuid(),'Senegal','+221','SN'),
(gen_random_uuid(),'Serbia','+381','RS'),
(gen_random_uuid(),'Seychelles','+248','SC'),
(gen_random_uuid(),'Sierra Leone','+232','SL'),
(gen_random_uuid(),'Singapore','+65','SG'),
(gen_random_uuid(),'Slovakia','+421','SK'),
(gen_random_uuid(),'Slovenia','+386','SI'),
(gen_random_uuid(),'Solomon Islands','+677','SB'),
(gen_random_uuid(),'Somalia','+252','SO'),
(gen_random_uuid(),'South Africa','+27','ZA'),
(gen_random_uuid(),'South Sudan','+211','SS'),
(gen_random_uuid(),'South Georgia and the South Sandwich Islands','+500','GS'),
(gen_random_uuid(),'Spain','+34','ES'),
(gen_random_uuid(),'Sri Lanka','+94','LK'),
(gen_random_uuid(),'Sudan','+249','SD'),
(gen_random_uuid(),'Suriname','+597','SR'),
(gen_random_uuid(),'Svalbard and Jan Mayen','+47','SJ'),
(gen_random_uuid(),'Swaziland','+268','SZ'),
(gen_random_uuid(),'Sweden','+46','SE'),
(gen_random_uuid(),'Switzerland','+41','CH'),
(gen_random_uuid(),'Syrian Arab Republic','+963','SY'),
(gen_random_uuid(),'Taiwan','+886','TW'),
(gen_random_uuid(),'Tajikistan','+992','TJ'),
(gen_random_uuid(),'Tanzania, United Republic of Tanzania','+255','TZ'),
(gen_random_uuid(),'Thailand','+66','TH'),
(gen_random_uuid(),'Timor-Leste','+670','TL'),
(gen_random_uuid(),'Togo','+228','TG'),
(gen_random_uuid(),'Tokelau','+690','TK'),
(gen_random_uuid(),'Tonga','+676','TO'),
(gen_random_uuid(),'Trinidad and Tobago','+1868','TT'),
(gen_random_uuid(),'Tunisia','+216','TN'),
(gen_random_uuid(),'Turkey','+90','TR'),
(gen_random_uuid(),'Turkmenistan','+993','TM'),
(gen_random_uuid(),'Turks and Caicos Islands','+1649','TC'),
(gen_random_uuid(),'Tuvalu','+688','TV'),
(gen_random_uuid(),'Uganda','+256','UG'),
(gen_random_uuid(),'Ukraine','+380','UA'),
(gen_random_uuid(),'United Arab Emirates','+971','AE'),
(gen_random_uuid(),'United Kingdom','+44','GB'),
(gen_random_uuid(),'Uruguay','+598','UY'),
(gen_random_uuid(),'Uzbekistan','+998','UZ'),
(gen_random_uuid(),'Vanuatu','+678','VU'),
(gen_random_uuid(),'Venezuela, Bolivarian Republic of Venezuela','+58','VE'),
(gen_random_uuid(),'Vietnam','+84','VN'),
(gen_random_uuid(),'Virgin Islands, British','+1284','VG'),
(gen_random_uuid(),'Virgin Islands, U.S.','+1340','VI'),
(gen_random_uuid(),'Wallis and Futuna','+681','WF'),
(gen_random_uuid(),'Yemen','+967','YE'),
(gen_random_uuid(),'Zambia','+260','ZM'),
(gen_random_uuid(),'Zimbabwe','+263','ZW');`;

export const statusesTabInitData = `insert into statuses (id,status) values (gen_random_uuid(),'Active'),(gen_random_uuid(),'Inactive'),(gen_random_uuid(),'Pending'),(gen_random_uuid(),'Deleted');`;

export const usersTabInitData = `insert into users (id,email,password_hash,first_name,last_name,full_name,gender,dob,phone,address1,address2,city,state,country,zip_code,status) values(gen_random_uuid(),'admin@admin.com','8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918','Admin','Admin','Admin Admin','Male','1990-10-07','9876543210','100, Main Street','ABC Apartment','Chennai','Tamilnadu','IN',40170,'Active'
),(gen_random_uuid(),'kumar@test.com','5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8','Kumar','G','Kumar G','Male','10-07-1996','9874561230','12, Main Street','XYZ Apartment','Chennai','Tamilnadu','IN',62700,'Active');`;
